name: farm
favicon: null
layout_spectrum: 0.9202156665269285
typography_spectrum: 0.17453981447033584
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4438120308332145
  lightness: 0.6404127238783985
  saturation: 0.3608353629242629
  rhythmicContrast: 0.5262131267227232
purpose: []
